development:
  dialect: mysql
  database: goffee
  user: root
  password: root
  host: {{ envOr "MYSQL_HOST" "127.0.0.1"  }}
  port: {{ envOr "MYSQL_PORT" "3306"  }}
  pool: 5
  encoding: utf8mb4_general_ci
